name: Running Testkube Tests.

on:
  push:
    branches:
      - main

jobs:
  test_worflow:
    name: test workflow for local minikube.
    runs-on: self-hosted
    steps:
      - name: Run test
        uses: kubeshop/testkube-run-action@v1
        with:
        # Instance
          organization: ${{ secrets.TkOrganization }}
          environment: ${{ secrets.TkEnvironment }}
          token: ${{ secrets.TkToken }}
          url: https://api.testkube.dev/
          test: curl-url-test
